<?php

declare(strict_types=1);

namespace Cortex\Docker;

use Symfony\Component\Yaml\Yaml;

/**
 * Generates docker-compose override files with port offsets
 */
class ComposeOverrideGenerator
{
    private const OVERRIDE_FILE = 'docker-compose.override.yml';
    private const HEADER_COMMENT = <<<YAML
# Generated by Cortex CLI - DO NOT EDIT MANUALLY
# This file is automatically created to prevent port conflicts
# Run 'cortex down' to remove this file

YAML;

    /**
     * Generate override file with port offset and container name handling
     */
    public function generate(string $composeFile, int $portOffset, ?string $namespacePrefix = null): void
    {
        if ($portOffset === 0 && $namespacePrefix === null) {
            // No override needed
            return;
        }

        if (!file_exists($composeFile)) {
            throw new \RuntimeException("Compose file not found: {$composeFile}");
        }

        // Parse original compose file
        $content = file_get_contents($composeFile);
        if ($content === false) {
            throw new \RuntimeException("Failed to read compose file: {$composeFile}");
        }

        $config = Yaml::parse($content);

        if (!isset($config['services'])) {
            return;
        }

        // Build override structure
        $override = [
            'services' => [],
        ];

        foreach ($config['services'] as $serviceName => $service) {
            $serviceOverride = [];

            // Handle port offset
            if (isset($service['ports']) && $portOffset > 0) {
                $newPorts = [];
                foreach ($service['ports'] as $portMapping) {
                    $newPort = $this->applyOffset($portMapping, $portOffset);
                    if ($newPort !== null) {
                        $newPorts[] = $newPort;
                    }
                }

                if (!empty($newPorts)) {
                    $serviceOverride['ports'] = $newPorts;
                }
            }

            // Handle container_name prefixing for namespace isolation
            if ($namespacePrefix !== null && isset($service['container_name'])) {
                // Prefix the container name with namespace
                $serviceOverride['container_name'] = $namespacePrefix . '-' . $service['container_name'];
            }

            if (!empty($serviceOverride)) {
                $override['services'][$serviceName] = $serviceOverride;
            }
        }

        // Write override file
        if (!empty($override['services'])) {
            $this->writeOverrideFile($override);
        }
    }

    /**
     * Delete the override file
     */
    public function cleanup(): void
    {
        $overridePath = getcwd() . '/' . self::OVERRIDE_FILE;
        if (file_exists($overridePath)) {
            unlink($overridePath);
        }
    }

    /**
     * Apply port offset to a port mapping
     */
    private function applyOffset(mixed $portMapping, int $offset): ?string
    {
        if (is_string($portMapping)) {
            $parts = explode(':', $portMapping);

            if (count($parts) === 2) {
                // "80:80" format
                $hostPort = (int) $parts[0];
                $containerPort = $parts[1];
                return ($hostPort + $offset) . ':' . $containerPort;
            } elseif (count($parts) === 3) {
                // "127.0.0.1:80:80" format
                $interface = $parts[0];
                $hostPort = (int) $parts[1];
                $containerPort = $parts[2];
                return $interface . ':' . ($hostPort + $offset) . ':' . $containerPort;
            }
        }

        // For complex formats, return as-is (could be enhanced later)
        return null;
    }

    /**
     * Write the override file to disk
     *
     * @param array<string, mixed> $override
     */
    private function writeOverrideFile(array $override): void
    {
        // Docker Compose v2 merges arrays by default
        // Use !override tag to force replacement instead of merging
        $yaml = Yaml::dump($override, 10, 2);
        
        // Add !override tag to ports arrays to prevent merging with base file
        // This ensures only the offset ports are used, not the original + offset
        $yaml = preg_replace('/^(\s+ports:)$/m', '$1 !override', $yaml);
        
        $content = self::HEADER_COMMENT . $yaml;

        $overridePath = getcwd() . '/' . self::OVERRIDE_FILE;
        file_put_contents($overridePath, $content);
    }
}
