<?php

declare(strict_types=1);

namespace Cortex\Docker;

use Symfony\Component\Yaml\Yaml;

/**
 * Generates docker-compose override files with port offsets
 */
class ComposeOverrideGenerator
{
    private const OVERRIDE_FILE = 'docker-compose.override.yml';
    private const HEADER_COMMENT = <<<YAML
# Generated by Cortex CLI - DO NOT EDIT MANUALLY
# This file is automatically created to prevent port conflicts
# Run 'cortex down' to remove this file

YAML;

    /**
     * Generate override file with port offset applied
     */
    public function generate(string $composeFile, int $portOffset): void
    {
        if ($portOffset === 0) {
            // No offset needed, don't generate override
            return;
        }

        if (!file_exists($composeFile)) {
            throw new \RuntimeException("Compose file not found: {$composeFile}");
        }

        // Parse original compose file
        $content = file_get_contents($composeFile);
        if ($content === false) {
            throw new \RuntimeException("Failed to read compose file: {$composeFile}");
        }

        $config = Yaml::parse($content);

        if (!isset($config['services'])) {
            return;
        }

        // Build override structure
        $override = [
            'services' => [],
        ];

        foreach ($config['services'] as $serviceName => $service) {
            if (!isset($service['ports'])) {
                continue;
            }

            $newPorts = [];
            foreach ($service['ports'] as $portMapping) {
                $newPort = $this->applyOffset($portMapping, $portOffset);
                if ($newPort !== null) {
                    $newPorts[] = $newPort;
                }
            }

            if (!empty($newPorts)) {
                $override['services'][$serviceName] = [
                    'ports' => $newPorts,
                ];
            }
        }

        // Write override file
        if (!empty($override['services'])) {
            $this->writeOverrideFile($override);
        }
    }

    /**
     * Delete the override file
     */
    public function cleanup(): void
    {
        $overridePath = getcwd() . '/' . self::OVERRIDE_FILE;
        if (file_exists($overridePath)) {
            unlink($overridePath);
        }
    }

    /**
     * Apply port offset to a port mapping
     */
    private function applyOffset(mixed $portMapping, int $offset): ?string
    {
        if (is_string($portMapping)) {
            $parts = explode(':', $portMapping);

            if (count($parts) === 2) {
                // "80:80" format
                $hostPort = (int) $parts[0];
                $containerPort = $parts[1];
                return ($hostPort + $offset) . ':' . $containerPort;
            } elseif (count($parts) === 3) {
                // "127.0.0.1:80:80" format
                $interface = $parts[0];
                $hostPort = (int) $parts[1];
                $containerPort = $parts[2];
                return $interface . ':' . ($hostPort + $offset) . ':' . $containerPort;
            }
        }

        // For complex formats, return as-is (could be enhanced later)
        return null;
    }

    /**
     * Write the override file to disk
     *
     * @param array<string, mixed> $override
     */
    private function writeOverrideFile(array $override): void
    {
        $yaml = Yaml::dump($override, 10, 2);
        $content = self::HEADER_COMMENT . $yaml;

        $overridePath = getcwd() . '/' . self::OVERRIDE_FILE;
        file_put_contents($overridePath, $content);
    }
}
